/**
 * 3D emoji artwork from Microsoft Fluent Emoji (MIT license, see assets/emoji/LICENSE),
 * resized to 192px. Used for game elements and category tiles. Blue-heavy artwork is left out on purpose.
 */
export const Emoji = {
  alarm: require('@/assets/emoji/alarm.png'),
  banknote: require('@/assets/emoji/banknote.png'),
  bulb: require('@/assets/emoji/bulb.png'),
  cart: require('@/assets/emoji/cart.png'),
  check: require('@/assets/emoji/check.png'),
  coin: require('@/assets/emoji/coin.png'),
  compass: require('@/assets/emoji/compass.png'),
  crown: require('@/assets/emoji/crown.png'),
  crystalBall: require('@/assets/emoji/crystal-ball.png'),
  fire: require('@/assets/emoji/fire.png'),
  gift: require('@/assets/emoji/gift.png'),
  graduationCap: require('@/assets/emoji/graduation-cap.png'),
  hamburger: require('@/assets/emoji/hamburger.png'),
  handbag: require('@/assets/emoji/handbag.png'),
  headphone: require('@/assets/emoji/headphone.png'),
  heart: require('@/assets/emoji/heart.png'),
  house: require('@/assets/emoji/house.png'),
  ledger: require('@/assets/emoji/ledger.png'),
  lock: require('@/assets/emoji/lock.png'),
  lotion: require('@/assets/emoji/lotion.png'),
  microphone: require('@/assets/emoji/microphone.png'),
  moneyBag: require('@/assets/emoji/money-bag.png'),
  package: require('@/assets/emoji/package.png'),
  pill: require('@/assets/emoji/pill.png'),
  popcorn: require('@/assets/emoji/popcorn.png'),
  rocket: require('@/assets/emoji/rocket.png'),
  scale: require('@/assets/emoji/scale.png'),
  scroll: require('@/assets/emoji/scroll.png'),
  seedling: require('@/assets/emoji/seedling.png'),
  sparkles: require('@/assets/emoji/sparkles.png'),
  star: require('@/assets/emoji/star.png'),
  sun: require('@/assets/emoji/sun.png'),
  swords: require('@/assets/emoji/swords.png'),
  taxi: require('@/assets/emoji/taxi.png'),
  trophy: require('@/assets/emoji/trophy.png'),
  twoHearts: require('@/assets/emoji/two-hearts.png'),
  warning: require('@/assets/emoji/warning.png'),
  zap: require('@/assets/emoji/zap.png'),
} as const;

export type EmojiName = keyof typeof Emoji;
